"use client";

import { useState, type ReactNode } from "react";
import useSWR from "swr";
import { toast } from "sonner";
import {
  ArrowSquareOut,
  CheckCircle,
  Cloud,
  Cpu,
  HardDrives,
  Key,
  Lock,
  UserCircle,
  Warning,
} from "@phosphor-icons/react/dist/ssr";

import type {
  ClaudeSettings,
  OauthCodeError,
  OauthStart,
  OllamaModelsResponse,
  ProviderTest,
} from "@/lib/types";

import { endpoints } from "@/lib/endpoints";
import { ProxyError, errorMessage, proxyFetch, proxyFetcher, proxyMutate } from "@/lib/proxy-fetcher";
import { cn } from "@/lib/utils";

type Mode = ClaudeSettings["mode"];

function ModeNotice({ summary, advanced }: { summary: string; advanced: ReactNode }) {
  return (
    <div className="flex items-start gap-2.5 rounded-lg px-4 py-3 text-[12.5px] leading-relaxed bg-status-warning-soft border border-status-warning/30 text-status-warning shadow-sm">
      <Warning size={16} weight="duotone" className="mt-0.5 shrink-0" />
      <div className="min-w-0">
        <p className="font-medium">{summary}</p>
        <details className="mt-2.5">
          <summary className="cursor-pointer text-[11.5px] font-bold uppercase tracking-widest text-status-warning/80 hover:text-status-warning transition-colors">
            Advanced configuration
          </summary>
          <div className="mt-2 space-y-1.5 text-[12px] opacity-90">
            {advanced}
          </div>
        </details>
      </div>
    </div>
  );
}

const MODES: {
  key: Mode;
  label: string;
  blurb: string;
  Icon: typeof Key;
}[] = [
  {
    key: "subscription",
    label: "Claude subscription",
    blurb: "Sign in through the browser. Local development.",
    Icon: UserCircle,
  },
  {
    key: "anthropic_api",
    label: "Anthropic API key",
    blurb: "A key from the Claude Console, billed per token.",
    Icon: Key,
  },
  {
    key: "bedrock",
    label: "Amazon Bedrock",
    blurb: "On Fargate the task role supplies the credentials.",
    Icon: Cloud,
  },
  {
    key: "ollama",
    label: "Ollama (local dev)",
    blurb: "Host-installed Ollama — local or :cloud models.",
    Icon: HardDrives,
  },
  {
    key: "nim",
    label: "NVIDIA NIM",
    blurb: "Uses local LiteLLM proxy with automatic RPM backoffs.",
    Icon: Cpu,
  },
];

const FIELD_LABELS: Record<string, { label: string; hint?: string; placeholder?: string }> = {
  oauthToken: {
    label: "Subscription token",
    hint: "Generated by `claude setup-token`. Valid for a year.",
    placeholder: "sk-ant-oat…",
  },
  apiKey: { label: "API key", placeholder: "sk-ant-api03-…" },
  bedrockApiKey: {
    label: "Bedrock API key",
    hint: "Optional. Leave empty on Fargate — the task role is used instead.",
    placeholder: "ABSK…",
  },
  baseUrl: { label: "Base URL", placeholder: "http://litellm:4000" },
  awsRegion: { label: "AWS region", placeholder: "us-east-1" },
  model: {
    label: "Model",
    hint: "An alias like `sonnet`, or a full Bedrock inference-profile ID.",
    placeholder: "sonnet",
  },
  smallFastModel: {
    label: "Background model",
    hint: "Optional. Used for session titles and other background work.",
    placeholder: "us.anthropic.claude-haiku-4-5-20251001-v1:0",
  },
};

function fieldMeta(
  mode: Mode,
  key: string,
): { label: string; hint?: string; placeholder?: string } {
  if (mode === "bedrock") {
    if (key === "awsRegion") {
      return {
        label: "AWS region",
        placeholder: "ap-south-1",
        hint: "The region where Bedrock runs. India uses a different profile prefix than US or EU.",
      };
    }
    if (key === "bedrockApiKey") {
      return {
        label: "Bedrock API key",
        placeholder: "ABSK…",
        hint: "Saved to the repo `.env` as AWS_BEARER_TOKEN_BEDROCK (file mode 600, gitignored). Leave empty on Fargate — the task role is used instead.",
      };
    }
    if (key === "model") {
      return {
        label: "Model",
        placeholder: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
        hint: "A full cross-region inference-profile ID — not a bare foundation-model ID.",
      };
    }
    if (key === "smallFastModel") {
      return {
        label: "Background model",
        placeholder: "global.anthropic.claude-haiku-4-5-20251001-v1:0",
        hint: "Optional. Haiku for session titles; leave empty to reuse the main model. Maps to the haiku alias.",
      };
    }
  }
  if (mode === "nim") {
    if (key === "apiKey") {
      return {
        label: "NIM API key",
        placeholder: "nvapi-...",
        hint: "Saved to the repo `.env` as NVIDIA_NIM_API_KEY (gitignored).",
      };
    }
    if (key === "model") {
      return {
        label: "Model",
        placeholder: "nvidia_nim/meta/llama-3.1-70b-instruct",
        hint: "The LiteLLM model string to request through the proxy.",
      };
    }
  }
  if (mode === "ollama") {
    if (key === "baseUrl") {
      return {
        label: "Ollama base URL",
        placeholder: "http://host.docker.internal:11434",
        hint: "Docker: host.docker.internal:11434. Native dev on the host: http://localhost:11434.",
      };
    }
    if (key === "model") {
      return {
        label: "Model",
        placeholder: "qwen2.5-coder:32b",
        hint: "Local: qwen2.5-coder:32b. Cloud: glm-5:cloud, kimi-k2.5:cloud (requires ollama pull).",
      };
    }
    if (key === "smallFastModel") {
      return {
        label: "Background model",
        placeholder: "gemma4:31b-cloud",
        hint: "Maps to the haiku alias. Sonnet, opus, and subagents use the main model automatically.",
      };
    }
  }
  return FIELD_LABELS[key] ?? { label: key };
}

/**
 * Which Claude Code this installation talks to.
 *
 * Before this screen existed the worker inherited whatever environment its shell
 * had, so authentication was invisible from inside the app. The environment
 * still wins — on Fargate the credentials come from Secrets Manager and must not
 * be editable here — and any field it sets is shown locked rather than silently
 * ignored.
 */
export function ClaudeSettingsClient() {
  const { data, error, mutate, isLoading } = useSWR<ClaudeSettings>(
    "/api/proxy/settings/claude",
    proxyFetcher,
  );

  // The user's explicit pick wins; until they make one the server's saved mode
  // is what shows. Derived rather than copied in an effect, which is what used
  // to make switching provider render one frame of the previous one's fields.
  const [pickedMode, setPickedMode] = useState<Mode | null>(null);
  const [edits, setEdits] = useState<{ key: string; values: Record<string, string> } | null>(null);
  const [saving, setSaving] = useState(false);
  const [testing, setTesting] = useState(false);
  const [result, setResult] = useState<ProviderTest | null>(null);
  const [signIn, setSignIn] = useState<{ session: string; url: string } | null>(null);
  const [code, setCode] = useState("");
  const [finishing, setFinishing] = useState(false);
  const [ollamaModels, setOllamaModels] = useState<string[]>([]);
  const [loadingModels, setLoadingModels] = useState(false);

  // Provider credentials are not an estimator's to read or change, so the API
  // refuses them. Say which it is rather than sitting on "Reading…" for ever.
  if (error) {
    const forbidden = error instanceof ProxyError && error.status === 403;
    return (
      <div className="px-7 py-6">
        <div className="rounded-lg px-4 py-3 text-[13px] font-medium bg-status-error-soft border border-status-error/30 text-status-error shadow-sm">
          {forbidden
            ? "You do not have permission to configure the provider. Ask whoever administers this installation."
            : `Could not read the configuration: ${errorMessage(error)}`}
        </div>
      </div>
    );
  }

  if (isLoading || !data) {
    return (
      <div className="px-7 py-6 text-[13px] font-medium text-tx-muted">
        Reading the current configuration…
      </div>
    );
  }

  const mode: Mode = pickedMode ?? data.mode;

  // Not `data.fields`, which only covers the saved mode - picking a provider you
  // have not saved yet would render an empty form with no way to configure it.
  const fields = data.schema?.[mode] ?? (mode === data.mode ? data.fields : {});

  // A different provider, or a fresh save, is a different form. Keying the
  // draft off both reseeds it without an effect - switching provider starts
  // from that provider's own stored values, not from what was typed for the last.
  const draftKey = `${mode}:${data.updatedAt ?? ""}`;
  const draft =
    edits?.key === draftKey
      ? edits.values
      : Object.fromEntries(Object.entries(fields).map(([key, field]) => [key, field.value ?? ""]));

  const fieldKeys = Object.keys(fields);

  function setField(key: string, value: string) {
    setEdits({ key: draftKey, values: { ...draft, [key]: value } });
  }

  function pickMode(next: Mode) {
    setPickedMode(next);
    setResult(null);
  }

  function payload() {
    const body: Record<string, string> = { mode };
    for (const [key, field] of Object.entries(fields)) {
      if (field.locked) continue;
      const value = draft[key];
      if (value) body[key] = value;
    }
    return body;
  }

  async function save() {
    setSaving(true);
    try {
      await proxyMutate("/api/proxy/settings/claude", { method: "PUT", body: payload() });
      toast.success("Provider saved", {
        description: "The next job will use it — the worker does not need a restart.",
      });
      setEdits(null);
      mutate();
    } catch (problem) {
      toast.error("Could not save that", { description: errorMessage(problem) });
    } finally {
      setSaving(false);
    }
  }

  async function test() {
    setTesting(true);
    setResult(null);
    try {
      const body = await proxyMutate<ProviderTest>("/api/proxy/settings/claude/test", {
        body: payload(),
      });
      setResult(body);
      if (body.ok) toast.success("Claude Code answered");
      else toast.error("No answer from Claude Code");
    } catch (problem) {
      toast.error("Could not reach the API", { description: errorMessage(problem) });
    } finally {
      setTesting(false);
    }
  }

  async function refreshOllamaModels() {
    setLoadingModels(true);
    try {
      const params = new URLSearchParams();
      const baseUrl = draft.baseUrl?.trim();
      if (baseUrl) params.set("baseUrl", baseUrl);
      const query = params.toString();
      const body = await proxyFetcher<OllamaModelsResponse>(
        `/api/proxy/settings/ollama/models${query ? `?${query}` : ""}`,
      );
      const names = body.models.map((entry) => entry.name).filter(Boolean) as string[];
      setOllamaModels(names);
      if (names.length === 0) {
        toast.message("No models found", {
          description: "Pull one on the host: ollama pull qwen2.5-coder:32b",
        });
      } else {
        toast.success(`Found ${names.length} model${names.length === 1 ? "" : "s"}`);
      }
    } catch (problem) {
      toast.error("Could not list Ollama models", {
        description: errorMessage(problem) || "Is Ollama running on the host?",
      });
    } finally {
      setLoadingModels(false);
    }
  }

  async function startSignIn() {
    try {
      const body = await proxyMutate<OauthStart>("/api/proxy/settings/claude/oauth/start");
      setSignIn({ session: body.session, url: body.url });
      window.open(body.url, "_blank", "noopener,noreferrer");
    } catch (problem) {
      toast.error("Could not start sign-in", { description: errorMessage(problem) });
    }
  }

  async function finishSignIn() {
    // One exchange per code. The submit is wired to both Enter and the button,
    // and an authorization code is single-use: the first call consumes the
    // session, so a second reaches a backend that has already closed it and
    // comes back without a `message`. That is what surfaces as the bare
    // "That code was not accepted" fallback below - a report of the double
    // submit rather than of anything wrong with the code the estimator pasted.
    if (!signIn || !code.trim() || finishing) return;
    setFinishing(true);
    try {
      return await exchangeCode(signIn);
    } finally {
      setFinishing(false);
    }
  }

  async function exchangeCode(session: { session: string; url: string }) {
    const response = await proxyFetch(endpoints.claudeOauthCode(), {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ session: session.session, code: code.trim() }),
    });
    // Whether the body was JSON at all. A proxy between the browser and the API
    // can answer for it: a Cloudflare tunnel replaces a 5xx body with its own
    // HTML page, so `.json()` throws, `detail` is empty, and every distinct
    // failure collapsed into the generic message below. The real error was
    // invisible - the API had said exactly what was wrong and nothing survived
    // to show it.
    let parsed = true;
    const body: { detail?: string | OauthCodeError } = await response
      .json()
      .catch(() => {
        parsed = false;
        return {} as { detail?: string | OauthCodeError };
      });
    if (!response.ok) {
      // A rejected code makes the CLI start a fresh authorization, so the link
      // on screen is already dead. Swap it for the new one rather than leaving
      // the estimator to retry against a challenge that no longer exists.
      const detail = body.detail ?? {};
      const structured: OauthCodeError = typeof detail === "string" ? { message: detail } : detail;
      if (structured.url) {
        setSignIn({ session: session.session, url: structured.url });
        setCode("");
      }
      const fallback = parsed
        ? "That code was not accepted"
        : `The sign-in failed with ${response.status}, and something between this page and the API replaced the explanation.`;
      toast.error(structured.message || fallback, {
        description:
          structured.hint ??
          (parsed
            ? undefined
            : "Try again over the local address rather than a tunnel - the API's own message will come through."),
      });
      return;
    }
    toast.success("Signed in to Claude Code");
    setSignIn(null);
    setCode("");
    mutate();
  }

  return (
    <div className="flex flex-col gap-6 p-8 bg-panel border border-subtle rounded-xl shadow-sm">
      <header className="flex flex-col sm:flex-row sm:items-baseline justify-between gap-4">
        <div>
          <h1 className="text-[20px] font-bold text-tx-primary tracking-tight">Claude Code</h1>
          <p className="mt-1 text-[13px] font-medium text-tx-secondary">
            Which model runs the extraction and pricing passes.
            {data.updatedBy ? ` Last changed by ${data.updatedBy}.` : ""}
          </p>
        </div>
        {!data.cliAvailable && (
          <span className="flex items-center gap-2 rounded-md px-3 py-2 text-[12.5px] font-medium bg-status-error-soft text-status-error">
            <Warning size={14} weight="duotone" />
            The CLI is not installed on the API host
          </span>
        )}
      </header>

      <div className="grid grid-cols-2 gap-3 xl:grid-cols-3">
        {MODES.map(({ key, label, blurb, Icon }) => {
          const on = mode === key;
          return (
            <button
              key={key}
              onClick={() => pickMode(key)}
              className={cn(
                "flex flex-col items-start gap-2 rounded-xl p-4 text-left transition-colors shadow-sm",
                on 
                  ? "bg-brand-soft border-2 border-brand-primary" 
                  : "bg-background border border-subtle hover:border-brand-border"
              )}
            >
              <Icon
                size={20}
                weight={on ? "bold" : "duotone"}
                className={on ? "text-brand-primary" : "text-tx-muted"}
              />
              <span
                className={cn(
                  "text-[13.5px] font-bold tracking-tight",
                  on ? "text-brand-primary" : "text-tx-primary"
                )}
              >
                {label}
              </span>
              <span className="text-[12.5px] font-medium leading-snug text-tx-secondary">
                {blurb}
              </span>
            </button>
          );
        })}
      </div>

      {mode === "bedrock" && (
        <ModeNotice
          summary="Use a cross-region inference-profile ID for Bedrock, not a bare foundation-model ID. On Fargate leave the API key empty — the task role is used."
          advanced={
            <>
              <p>
                A value like <code>anthropic.claude-sonnet-4-5-20250929-v1:0</code> is rewritten
                to <code>global.anthropic.…</code> in <code>ap-south-1</code> (or{" "}
                <code>us.</code> / <code>eu.</code> / <code>apac.</code> elsewhere).
              </p>
              <p>
                Phase agents declare <code>model: sonnet</code>; those aliases, and opus, are pinned
                to the configured model. Save writes the key into <code>.env</code> (gitignored) as
                well as Mongo, so native runs and the next worker job see it without a restart.
              </p>
            </>
          }
        />
      )}

      {mode === "ollama" && (
        <ModeNotice
          summary="Ollama runs on the host — no Ollama container is bundled. Pick a model with at least 64k context and verify tool output against the drawing."
          advanced={
            <>
              <p>
                Set <code>OLLAMA_CONTEXT_LENGTH=65536</code> before starting Ollama. Phase agents
                declare <code>model: sonnet</code>; in Ollama mode those aliases route to your
                configured model automatically.
              </p>
            </>
          }
        />
      )}

      {mode === "nim" && (
        <ModeNotice
          summary="Ensure the local LiteLLM proxy is running. Claude Code rate limiting retries are configured automatically."
          advanced={
            <>
              <p>
                Run <code>docker compose --profile oss up -d litellm</code> to start the proxy. NIM has a strict 40 requests-per-minute limit on free tier.
              </p>
            </>
          }
        />
      )}

      {mode === "subscription" && data.localDev && (
        <section className="rounded-xl p-5 bg-panel-muted border border-subtle shadow-sm">
          <h2 className="text-[14px] font-bold text-tx-primary tracking-tight">Sign in through the browser</h2>
          <p className="mt-1 text-[13px] font-medium text-tx-secondary">
            There is no browser inside the container, so Claude Code prints an authorization URL
            and waits for the code it gives you back. Local development only.
          </p>

          {!signIn ? (
            <button
              onClick={startSignIn}
              className="mt-4 flex items-center gap-1.5 rounded-md px-4 py-2.5 text-[13px] font-semibold bg-brand-primary text-white shadow-sm hover:bg-brand-primary/90 transition-colors"
            >
              <ArrowSquareOut size={16} weight="bold" />
              Sign in to Claude Code
            </button>
          ) : (
            <div className="mt-4 flex flex-col gap-3">
              <a
                href={signIn.url}
                target="_blank"
                rel="noopener noreferrer"
                className="truncate text-[13px] font-medium underline text-brand-primary hover:text-brand-primary/80 transition-colors"
              >
                {signIn.url}
              </a>
              <div className="flex gap-2">
                <input
                  autoFocus
                  value={code}
                  onChange={(event) => setCode(event.target.value)}
                  onKeyDown={(event) => event.key === "Enter" && finishSignIn()}
                  placeholder="Paste the code from the browser"
                  className="flex-1 rounded-md px-3 py-2 text-[13px] outline-none border border-brand-border bg-background text-tx-primary focus:ring-1 focus:ring-brand-primary transition-colors shadow-sm"
                />
                <button
                  onClick={finishSignIn}
                  disabled={finishing}
                  className="rounded-md px-4 py-2 text-[13px] font-semibold bg-brand-primary text-white shadow-sm hover:bg-brand-primary/90 transition-colors disabled:opacity-60"
                >
                  {finishing ? "Checking…" : "Finish"}
                </button>
              </div>
            </div>
          )}
        </section>
      )}

      {fieldKeys.length > 0 && (
        <section className="flex flex-col gap-4 rounded-xl p-5 bg-background border border-subtle shadow-sm">
          {fieldKeys.map((key) => {
            const field = fields[key];
            const meta = fieldMeta(mode, key);
            const showModelPicker = mode === "ollama" && key === "model";
            return (
              <label key={key} className="flex flex-col gap-1.5">
                <span className="flex items-center gap-2 text-[12.5px] font-semibold text-tx-primary">
                  {meta.label}
                  <code className="text-[11px] font-medium text-tx-muted px-1.5 py-0.5 rounded bg-panel-muted border border-subtle">
                    {field.variable}
                  </code>
                  {field.locked && (
                    <span className="flex items-center gap-1 rounded px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-widest bg-panel border border-subtle text-tx-muted shadow-sm">
                      <Lock size={10} weight="bold" />
                      set by env
                    </span>
                  )}
                </span>
                {showModelPicker && ollamaModels.length > 0 ? (
                  <select
                    value={draft[key] ?? ""}
                    disabled={field.locked}
                    onChange={(event) => setField(key, event.target.value)}
                    className="rounded-md px-3 py-2 text-[13px] outline-none border border-subtle bg-background text-tx-primary focus:ring-1 focus:ring-brand-border disabled:opacity-60 shadow-sm"
                  >
                    <option value="">Select a model…</option>
                    {ollamaModels.map((name) => (
                      <option key={name} value={name}>
                        {name}
                      </option>
                    ))}
                  </select>
                ) : (
                  <input
                    value={draft[key] ?? ""}
                    disabled={field.locked}
                    onChange={(event) => setField(key, event.target.value)}
                    placeholder={meta.placeholder}
                    autoComplete="off"
                    autoCorrect="off"
                    spellCheck={false}
                    className="rounded-md px-3 py-2 text-[13px] outline-none border border-subtle bg-background text-tx-primary placeholder:text-tx-muted focus:ring-1 focus:ring-brand-border disabled:opacity-60 shadow-sm"
                  />
                )}
                {showModelPicker && (
                  <button
                    type="button"
                    onClick={refreshOllamaModels}
                    disabled={loadingModels || field.locked}
                    className="self-start mt-1 rounded-md px-3 py-1.5 text-[12px] font-medium border border-subtle text-tx-secondary hover:bg-panel-muted transition-colors disabled:opacity-60"
                  >
                    {loadingModels ? "Refreshing…" : "Refresh models from Ollama"}
                  </button>
                )}
                {meta.hint && (
                  <span className="text-[12px] font-medium text-tx-muted mt-0.5">
                    {meta.hint}
                  </span>
                )}
              </label>
            );
          })}
        </section>
      )}

      <div className="flex items-center gap-3 pt-2">
        <button
          onClick={save}
          disabled={saving}
          className="rounded-md px-4 py-2.5 text-[13px] font-semibold bg-brand-primary text-white shadow-sm hover:bg-brand-primary/90 transition-colors disabled:opacity-60"
        >
          {saving ? "Saving…" : "Save"}
        </button>
        <button
          onClick={test}
          disabled={testing}
          className="rounded-md px-4 py-2.5 text-[13px] font-medium border border-subtle text-tx-secondary hover:bg-panel-muted transition-colors shadow-sm disabled:opacity-60"
        >
          {testing ? "Asking Claude Code…" : "Test connection"}
        </button>
        <span className="text-[12.5px] font-medium text-tx-muted">
          Test runs a real one-line pass against what is on screen, not what is saved.
        </span>
      </div>

      {result && (
        <div
          className={cn(
            "flex items-start gap-2.5 rounded-lg px-4 py-3 text-[12.5px] shadow-sm",
            result.ok 
              ? "bg-status-success-soft border border-status-success/30 text-status-success"
              : "bg-status-error-soft border border-status-error/30 text-status-error"
          )}
        >
          {result.ok ? (
            <CheckCircle size={16} weight="duotone" className="mt-0.5 shrink-0" />
          ) : (
            <Warning size={16} weight="duotone" className="mt-0.5 shrink-0" />
          )}
          <span>
            {result.ok ? (
              <>
                Answered through <strong className="font-bold">{result.provider.mode}</strong> on{" "}
                <strong className="font-bold">{result.provider.model}</strong>
                {result.provider.region ? ` in ${result.provider.region}` : ""}.
              </>
            ) : (
              result.error
            )}
            {result.provider.warnings && result.provider.warnings.length > 0 && (
              <span className="mt-1.5 block font-medium opacity-90">
                {result.provider.warnings.join(" ")}
              </span>
            )}
          </span>
        </div>
      )}
    </div>
  );
}
