"""POST /api/settings/claude/oauth/{start,code} - browser sign-in, for local development.

`claude setup-token` runs on a pseudo-terminal, prints an authorization URL, and
returns a one-year token once the code from the browser is pasted back. Process
handles stay in this process; session rows live in Mongo so another instance can
tell a stale or foreign session. `sweep_oauth_sessions` is the periodic cleanup
the module registers with the composition root.
"""
from __future__ import annotations

import asyncio
import os
import shutil
import socket
import time
import uuid
from datetime import datetime, timedelta, timezone
from typing import Any

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from cbc.modules.ops.infrastructure import secrets
from cbc.modules.ops.api import audit
from cbc.modules.ops.features.ClaudeOAuth.terminal import (
    URL_PATTERN,
    _DONE_PATTERN,
    _OAUTH_ERROR,
    _PROMPT_PATTERN,
    _TOKEN_PATTERN,
    _clean,
    _read_until,
)
from cbc.modules.ops.infrastructure.claude_config import DOC_ID, load_config
from cbc.modules.ops.infrastructure.collections import oauth_sessions, settings_collection
from cbc.modules.ops.api import provider
from cbc.shared.auth import Actor, require_admin

# Every settings route is admin-only: they read or write provider credentials,
# spawn CLI processes, or change how every bid behaves.
router = APIRouter(prefix="/api/settings", tags=["settings"], dependencies=[Depends(require_admin)])


# In-flight `claude setup-token` processes, keyed by the id handed to the
# browser. Process handles stay in-process; session metadata lives in Mongo so
# multi-worker deployments can detect stale or foreign-host sessions.
_PENDING: dict[str, dict[str, Any]] = {}


_PENDING_TTL = 600


API_INSTANCE_ID = f"{socket.gethostname()}-{os.getpid()}"


class OAuthCode(BaseModel):
    session: str
    code: str


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _is_local_dev() -> bool:
    return os.environ.get("APP_ENV", "development").lower() not in ("production", "prod")


def _sweep() -> None:
    for key, entry in list(_PENDING.items()):
        if time.time() - entry["startedAt"] > _PENDING_TTL:
            _close(key)


async def sweep_oauth_sessions() -> None:
    """Kill abandoned OAuth subprocesses and drop expired Mongo session rows."""
    _sweep()
    now = _now()
    expired = await oauth_sessions().find({"expiresAt": {"$lte": now}}).to_list(100)
    for row in expired:
        _close(row["_id"])
        await oauth_sessions().delete_one({"_id": row["_id"]})


def _close(key: str) -> None:
    entry = _PENDING.pop(key, None)
    if not entry:
        return
    try:
        entry["process"].kill()
    except Exception:
        pass
    try:
        os.close(entry["fd"])
    except Exception:
        pass


@router.post("/claude/oauth/start")
async def oauth_start() -> dict[str, Any]:
    """Begin `claude setup-token` and return the URL to open in a browser.

    The CLI drives this through a terminal prompt, so it needs a pty. There is no
    pty on Windows - the flow is reported as unavailable there rather than
    half-working, and the token can still be generated by hand and pasted in.
    """
    if not _is_local_dev():
        raise HTTPException(
            403,
            "Browser sign-in is a local development path. In production, configure "
            "a provider credential or an IAM role.",
        )

    try:
        import pty
    except ImportError:
        raise HTTPException(
            501,
            "This host has no pty, so the interactive flow cannot run. Run "
            "`claude setup-token` yourself and paste the token in as the "
            "subscription credential.",
        )

    binary = shutil.which("claude")
    if binary is None:
        raise HTTPException(503, "the Claude Code CLI is not installed on this host")

    _sweep()
    import subprocess

    controller, follower = pty.openpty()

    # A pty defaults to 80 columns and the CLI hard-wraps to it, which puts a
    # CRLF into the middle of both the authorization URL and anything else long.
    # The URL survived only because the terminal hyperlink escape carries an
    # unwrapped copy - not something to rely on. Give it a wide window instead.
    try:
        import fcntl
        import struct
        import termios

        fcntl.ioctl(follower, termios.TIOCSWINSZ, struct.pack("HHHH", 50, 400, 0, 0))
    except (ImportError, OSError):
        pass  # cosmetic; extraction still has the hyperlink copy to fall back on

    process = subprocess.Popen(
        [binary, "setup-token"],
        stdin=follower,
        stdout=follower,
        stderr=follower,
        close_fds=True,
    )
    os.close(follower)

    buffered = await asyncio.to_thread(_read_until, controller, URL_PATTERN, 60)
    match = URL_PATTERN.search(buffered)
    if not match:
        try:
            process.kill()
        finally:
            os.close(controller)
        raise HTTPException(
            504,
            "The CLI did not print an authorization URL. Output was: "
            + secrets.redact(_clean(buffered)[-500:]),
        )

    session = uuid.uuid4().hex
    expires = _now() + timedelta(seconds=_PENDING_TTL)
    await oauth_sessions().insert_one(
        {
            "_id": session,
            "hostId": API_INSTANCE_ID,
            "url": match.group(0),
            "startedAt": _now(),
            "expiresAt": expires,
        }
    )
    _PENDING[session] = {
        "process": process,
        "fd": controller,
        "startedAt": time.time(),
        "buffer": buffered,
    }
    return {"session": session, "url": match.group(0), "expiresIn": _PENDING_TTL}


@router.post("/claude/oauth/code")
async def oauth_code(body: OAuthCode, actor: Actor) -> dict[str, Any]:
    """Hand the browser's authorization code back to the CLI and store the token."""
    stored = await oauth_sessions().find_one({"_id": body.session})
    if not stored:
        raise HTTPException(404, "that sign-in has expired - start it again")
    if stored.get("hostId") != API_INSTANCE_ID:
        raise HTTPException(
            409,
            "this sign-in was started on another API instance; complete it there "
            "or start a new sign-in on this one",
        )

    entry = _PENDING.get(body.session)
    if not entry:
        await oauth_sessions().delete_one({"_id": body.session})
        raise HTTPException(404, "that sign-in has expired - start it again")

    code = body.code.strip()
    if not code:
        raise HTTPException(400, "no code supplied")

    # Carriage return, not newline. The prompt is an Ink TUI reading raw
    # keypresses, where Enter arrives as \r - a \n is accepted into the field and
    # never submitted, so the code sits there echoing asterisks until the read
    # times out. The code and the Enter go as separate writes because that is
    # what a paste followed by a keypress actually looks like.
    os.write(entry["fd"], code.encode("utf-8"))
    await asyncio.sleep(0.2)
    os.write(entry["fd"], b"\r")

    output = await asyncio.to_thread(_read_until, entry["fd"], _DONE_PATTERN, 120)

    # Read the token out of the cleaned text, not the raw stream. The CLI prints
    # it inside a styled panel, so colour escapes land between the characters and
    # a raw search misses a token that was created perfectly well - and the CLI
    # shows it exactly once, so losing it here means signing in all over again.
    readable = _clean(output)

    # Every rendering of the token, longest first, then verified for real.
    #
    # The CLI redraws its frame as it works, so the buffer holds the token several
    # times over, and an intermediate frame can carry a style escape spliced into
    # the middle of it. Stripping that escape takes a character of the token with
    # it - which is how a token that had been minted perfectly well was stored one
    # character short and rejected as an invalid bearer token, with nothing in the
    # UI to suggest anything but a bad credential. The complete rendering is the
    # longest one, and the only way to be sure is to make Claude Code use it.
    candidates = sorted(set(_TOKEN_PATTERN.findall(readable)), key=len, reverse=True)
    match = await _first_working_token(candidates)
    if not match:
        failure = _OAUTH_ERROR.search(readable)
        if candidates and not failure:
            _close(body.session)
            # Say what was extracted. A token is scraped out of a redrawing
            # terminal, and a rendering split or overwritten mid-token yields a
            # truncated candidate that is rejected for being wrong rather than
            # for being unauthorised - indistinguishable from a bad credential
            # unless the shapes are shown. Lengths and ends only; never the body.
            shapes = ", ".join(
                f"{len(c)} chars {c[:12]}…{c[-4:]}" for c in candidates[:4]
            )
            raise HTTPException(
                502,
                {
                    "message": "The CLI issued a token but Claude Code would not "
                    "accept it. It has to be generated again - the CLI shows it only "
                    "once.",
                    "hint": f"Tried {len(candidates)} reading(s): {shapes}. "
                    f"Claude Code said: {_LAST_VERIFY_ERROR['reason']!r}. "
                    "Start the sign-in again.",
                },
            )

        # A rejected code leaves the CLI on "Press Enter to retry", where it
        # swallows the next code as the keypress it is waiting for. Acknowledge it
        # here so the session is left back at the prompt, and a second attempt
        # works instead of hanging until the read times out.
        if not failure:
            _close(body.session)
            raise HTTPException(
                502,
                {
                    "message": "No token came back from the CLI. It reported: "
                    + secrets.redact(readable[-400:])
                },
            )

        os.write(entry["fd"], b"\r")
        retry_output = await asyncio.to_thread(_read_until, entry["fd"], _PROMPT_PATTERN, 30)

        # Retrying does not re-offer the same authorization - the CLI starts a new
        # one, with a new state and code challenge. Handing back the old URL would
        # send the estimator round a loop where every code is rejected for being
        # built against a challenge the CLI has already discarded.
        retry_url = URL_PATTERN.search(retry_output)
        raise HTTPException(
            502,
            {
                "message": failure.group(0),
                "url": retry_url.group(0) if retry_url else None,
                "hint": (
                    "That code was rejected. Use the new link - the previous one is "
                    "no longer valid."
                    if retry_url
                    else "Start the sign-in again."
                ),
            },
        )

    _close(body.session)
    await oauth_sessions().delete_one({"_id": body.session})

    token = match
    document = {
        "mode": provider.SUBSCRIPTION,
        "oauthToken": secrets.encrypt(token),
        "updatedAt": _now(),
        "updatedBy": actor,
    }
    # Signing in is a provider switch, so it has to clear the provider being
    # left. `$set` merges: without the `$unset` a Bedrock key and region stayed
    # on the document, and without persist_env_file the .env file still said
    # CLAUDE_CODE_USE_BEDROCK=1 afterwards. The saved-settings path does both;
    # this one did neither, so a sign-in left the two disagreeing.
    stale = {
        field
        for mode in provider.MODES
        for field in provider.FIELDS[mode]
        if field not in provider.FIELDS[provider.SUBSCRIPTION]
    }
    await settings_collection().update_one(
        {"_id": DOC_ID},
        {"$set": document, "$unset": {field: "" for field in sorted(stale)}},
        upsert=True,
    )
    await asyncio.to_thread(provider.persist_env_file, document)
    await audit.record(
        "settings.claude.oauth",
        actor,
        {},
        after={"mode": provider.SUBSCRIPTION},
        note="subscription token stored; value not recorded",
    )

    saved = await load_config()
    return {**provider.public_config(saved), "signedIn": True}


# Why the last candidate was refused. Set by `_first_working_token` so the
# failure can say whether the token was rejected as unauthorised - meaning it
# was scraped wrong - or whether the check itself never got an answer.
_LAST_VERIFY_ERROR: dict[str, str | None] = {"reason": None}


async def _first_working_token(candidates: list[str]) -> str | None:
    """Return the first candidate Claude Code actually accepts, or None.

    Verifying costs one short CLI round trip, which is worth it: the CLI shows the
    token exactly once, so storing a broken one silently is unrecoverable - the
    estimator sees a configured credential that fails on every job.
    """
    from cbc.modules.ops.api import claude_cli as runner

    _LAST_VERIFY_ERROR["reason"] = None
    for candidate in candidates:
        env, _ = provider.build_env({"mode": provider.SUBSCRIPTION, "oauthToken": candidate})
        problem = await asyncio.to_thread(runner.preflight, env, [candidate])
        if problem is None:
            return candidate
        _LAST_VERIFY_ERROR["reason"] = problem
    return None
