"""Pydantic schemas grouped by domain."""
from cbc.schemas.catalog import (
    PriceBook,
    PriceBookBase,
    PriceBookCreate,
    PriceBookUpdate,
    Product,
    ProductBase,
    ProductCreate,
    ProductUpdate,
)
from cbc.schemas.common import (
    CallKind,
    CostSource,
    Evidence,
    JobStatus,
    JobType,
    LineStatus,
    ProductType,
    Stage,
)
from cbc.schemas.documents import Document
from cbc.schemas.jobs import Job
from cbc.schemas.line_items import BulkAction, LineItem, LineItemCreate, LineItemUpdate
from cbc.schemas.reference import (
    CustomOtherMatrixReplace,
    FinishesUpdate,
    FrameDepthsUpdate,
    FrpConstantsUpdate,
    HagerAddersUpdate,
    LiteKitReplace,
    MarginFrameworkUpdate,
    SpecialCustomerMargin,
    SpecialMarginsUpdate,
    SpecialNetsUpdate,
    StockUpdate,
    TaxRatesUpdate,
    VendorCategoriesUpdate,
)
from cbc.schemas.quote import (
    HandOff,
    ProposalSettings,
    QuoteLine,
    QuoteLineCreate,
    QuoteLineUpdate,
    QuoteSettings,
    QuoteTotals,
)
from cbc.schemas.users import UserPublic
from cbc.schemas.versions import AlternateCreate, AlternateAssign, EstimateVersion, VersionCreate

__all__ = [
    "AlternateCreate",
    "AlternateAssign",
    "BulkAction",
    "CallKind",
    "CostSource",
    "Document",
    "EstimateVersion",
    "Evidence",
    "FinishesUpdate",
    "FrameDepthsUpdate",
    "FrpConstantsUpdate",
    "HandOff",
    "HagerAddersUpdate",
    "Job",
    "JobStatus",
    "JobType",
    "LineItem",
    "LineItemCreate",
    "LineItemUpdate",
    "LineStatus",
    "MarginFrameworkUpdate",
    "PriceBook",
    "PriceBookBase",
    "PriceBookCreate",
    "PriceBookUpdate",
    "Product",
    "ProductBase",
    "ProductCreate",
    "ProductType",
    "ProductUpdate",
    "ProposalSettings",
    "QuoteLine",
    "QuoteLineCreate",
    "QuoteLineUpdate",
    "QuoteSettings",
    "QuoteTotals",
    "Stage",
    "SpecialCustomerMargin",
    "SpecialMarginsUpdate",
    "SpecialNetsUpdate",
    "StockUpdate",
    "LiteKitReplace",
    "CustomOtherMatrixReplace",
    "VendorCategoriesUpdate",
    "TaxRatesUpdate",
    "UserPublic",
    "VersionCreate",
]
